### ISSUE TITLE
name should include react

### ISSUE THREAD

**Issue by charlierudolph** [Originate/create-factory-loader#1]
I find it odd that the name of the module and the loader doesn't mention react.

**Comment by alexdavid** [comment]
I originally was going to name  it react-create-factory-loader, but decided to shorten it since the name has to go in the require calls.

```coffeescript
require 'react-create-factory!./something'
```

isn't terrible though. Maybe I'll rename it

**Comment by alexdavid** [comment]
Closing since I'm deprecating this
